version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "cjaisingh"
    assignees:
      - "cjaisingh"
    commit-message:
      prefix: "security"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "cjaisingh"
    assignees:
      - "cjaisingh"
    commit-message:
      prefix: "ci"
      include: "scope"
