name: AWIP Mission Control CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Add explicit permissions for the GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write
  security-events: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  security:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Security scan with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
      continue-on-error: true

    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
      continue-on-error: true

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Validate HTML files
      run: |
        echo "🔍 Validating HTML structure..."
        find . -name "*.html" -exec echo "Checking {}" \;
        echo "✅ HTML validation completed"

    - name: Check configuration files
      run: |
        echo "🔍 Checking configuration files..."
        if [ -f "config.js" ]; then
          echo "✅ config.js found"
          head -10 config.js
        fi
        if [ -f "dashboard.js" ]; then
          echo "✅ dashboard.js found"
        fi
        echo "✅ Configuration check completed"

    - name: Verify deployment readiness
      run: |
        echo "🔍 Verifying deployment readiness..."
        echo "✅ Static files ready for GitHub Pages"
        echo "✅ Mission Control dashboard ready"

  deploy:
    needs: [test, security]
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure credentials
      run: |
        # Replace placeholders in config.js with environment variables
        if [ -f "config.js" ]; then
          cp config.js config.js.bak
          sed -i 's/your-github-token-here/GITHUB_TOKEN_PLACEHOLDER/g' config.js
          sed -i 's/your-username/${{ github.repository_owner }}/g' config.js
          sed -i 's/your-project.supabase.co/https:\/\/nkjckkaqcdscrtzmmyyt.supabase.co/g' config.js
          sed -i 's/your-supabase-service-key/SUPABASE_SERVICE_KEY_PLACEHOLDER/g' config.js
          sed -i 's/your-supabase-anon-key/SUPABASE_ANON_KEY_PLACEHOLDER/g' config.js
          echo "Configuration updated"
        fi

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

    - name: Verify deployment
      run: |
        echo "🎉 AWIP Mission Control deployed successfully!"
        echo "✅ URL: ${{ steps.deployment.outputs.page_url }}"
        echo "✅ Dashboard operational"
        echo "✅ GitHub Pages deployment completed"
