name: Deploy AWIP Dashboard

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Add explicit permissions for the GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure credentials
      run: |
        # Replace placeholders in config.js with environment variables
        cp config.js config.js.bak
        sed -i 's/your-github-token-here/GITHUB_TOKEN_PLACEHOLDER/g' config.js
        sed -i 's/your-username/${{ github.repository_owner }}/g' config.js
        sed -i 's/your-project.supabase.co/https:\/\/nkjckkaqcdscrtzmmyyt.supabase.co/g' config.js
        sed -i 's/your-supabase-service-key/SUPABASE_SERVICE_KEY_PLACEHOLDER/g' config.js
        sed -i 's/your-supabase-anon-key/SUPABASE_ANON_KEY_PLACEHOLDER/g' config.js
        echo "Configuration updated"

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
